### ISSUE TITLE
Training model with sklearn

### ISSUE THREAD

**Issue by younes200** [pagesjaunes/spacy-french-models#1]
Hi,
Thanks for sharing the model, I'm using it with Rasa.ai which combine sklearn under the hood. so I run a train process with the model but it end up with this exception :
Any idea ? thank you in advance.
```
INFO:root:Trying to load spacy model with name 'fr'
INFO:root:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-fr'.
INFO:root:Training data stats: 
  - intent examples: 51 (4 distinct intents)
  - found intents: affirm, goodbye, greet, restaurant_search
  - entity examples: 7 (2 distinct entities)
  - found entities: cuisine, location

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Workspace/Projects/tests/rasa_nlu/rasa_nlu/train.py", line 81, in <module>
    do_train(config)
  File "/Users/Workspace/Projects/tests/rasa_nlu/rasa_nlu/train.py", line 71, in do_train
    trainer.train(training_data)
  File "rasa_nlu/model.py", line 186, in train
    updates = component.train(*args)
  File "rasa_nlu/classifiers/sklearn_intent_classifier.py", line 90, in train
    self.clf.fit(X, y)
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 945, in fit
    return self._fit(X, y, groups, ParameterGrid(self.param_grid))
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 564, in _fit
    for parameters in parameter_iterable
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 238, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/svm/base.py", line 151, in fit
    X, y = check_X_y(X, y, dtype=np.float64, order='C', accept_sparse='csr')
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/utils/validation.py", line 521, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/Users/Workspace/Projects/tests/rasa_nlu/lib/python2.7/site-packages/sklearn/utils/validation.py", line 424, in check_array
    context))
ValueError: Found array with 0 feature(s) (shape=(40, 0)) while a minimum of 1 is required.
```

**Comment by Tpt** [comment]
It's probably because this model does not contains word vectors and Rasa NLU relies on them.

**Comment by younes0x53** [comment]
can we add the word vectors with https://github.com/explosion/spacy-dev-resources/blob/master/training/word_vectors.py ?

**Comment by thomasgirault** [comment]
Yes I will add word embeddings in next releases. 
It would be easy to add a model trained from Wikipedia for example.
I am too busy now by I will try work on it next week.

**Comment by Tpt** [comment]
Great! Thank you! https://github.com/explosion/spacy-dev-resources/tree/master/vocab allows to do it fairly easily
