### ISSUE TITLE
Morphology `KeyError` while processing '\t'

### ISSUE THREAD

**Issue by f11r** [pagesjaunes/spacy-french-models#5]
Great to see a first (community created) french model.

When analysing '\t' I get an `KeyError` in `spacy.morphology.Morphology.assign_tag_id (spacy/morphology.cpp:4681)()`.

## Steps to reproduce:
~~~
docker run -ti fedora:25 bash
dnf install python3-devel python3-pip gcc-c++ redhat-rpm-config
pip3 install spacy==1.8.0
pip3 install https://github.com/pagesjaunes/spacy-french-models/releases/download/v0.0.1-alpha/fr_model-0.0.1.tar.gz
python3 -m spacy link fr_model fr_default --force

python3 -c "import spacy; nlp = spacy.load('fr_default'); nlp('\t')"
~~~

Output:
~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/spacy/language.py", line 320, in __call__
    proc(doc)
  File "spacy/tagger.pyx", line 212, in spacy.tagger.Tagger.__call__ (spacy/tagger.cpp:6245)
  File "spacy/morphology.pyx", line 76, in spacy.morphology.Morphology.assign_tag_id (spacy/morphology.cpp:4681)
KeyError: 172049
~~~

Not sure whether that is a problem with the french model or actually with spacy itself. Maybe @honnibal or @ines can take a look at this as well?

**Comment by thomasgirault** [comment]
Thank you for your feedback. This issue does not occur with the en_core_web_sm model. So, it is probably a bug linked to this French model. Pending correction, a simple workaround would be to replace the symbol '\t' with a space.

**Comment by Tpt** [comment]
This issue is because Spacy assumes that the internal POS tag 'SP' (for 'SPACE') exists.
Every model should have in its tag_map `'SP': {POS: SPACE}`

See: https://github.com/explosion/spaCy/blob/40e30242415723f01aeab281d6cda1d1c66a4189/spacy/morphology.pyx#L76
